server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  main:
    allow-circular-references: true
  datasource:
    password: abc123456
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 527976125196-5b3om6dhrh7flio3q5lcq9051gkgljgv.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile           
          facebook:
            client-id: 1447393295719084
            client-secret: aa09148a160bac8297050360c7e2ba17
            scope:
            - email
            - public_profile
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

      


